title: Kevin Li’s GitHub Projects Page
description: Builder, tinkerer, and explorer of all things that can be poked and prodded with a keyboard or mouse. Ever optimistic believer of Murphy’s Law. Can be found vacationing in Debugging Hell.
theme: jekyll-theme-midnight
